=== sjimmaz322/Lenguaje-de-Marcas/XML/Factura_DTD/factura.dtd
<!ENTITY  % datos "nombre, (dir|dir_env), poblacion, provincia">
<!ELEMENT factura (datos_empresa, datos_cliente, datos_factura)>
<!ATTLIST factura n_fac ID #REQUIRED>
<!ELEMENT datos_empresa (%datos;, cif, telefono, fax)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT dir_env (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ATTLIST poblacion cod_postal CDATA #REQUIRED>
<!ELEMENT datos_cliente (%datos;)>
<!ATTLIST datos_cliente n_cli ID #REQUIRED>
<!ELEMENT datos_factura (fecha, linea+, base, cuota_iva, total)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT base (#PCDATA)>
<!ELEMENT cuota_iva (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ATTLIST datos_factura
	n_ped ID #REQUIRED
	iva (16) #REQUIRED
	f_pago (efectivo|tarjeta|bizum) #REQUIRED
	moneda CDATA #FIXED "euro"
>
<!ELEMENT linea (ref, desc, cant, precio, importe)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT cant (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT importe (#PCDATA)>

=== sjimmaz322/Lenguaje-de-Marcas/XML/Factura_DTD/factura.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE factura SYSTEM "factura.dtd">
<!--
<!DOCTYPE factura [
<!ELEMENT factura (datos_empresa, datos_cliente, datos_factura)>
<!ATTLIST factura n_fac ID #REQUIRED>
<!ELEMENT datos_empresa (nombre, (dir|dir_env), poblacion, provincia, cif, telefono, fax)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT dir_env (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ATTLIST poblacion cod_postal CDATA #REQUIRED>
<!ELEMENT datos_cliente (nombre, (dir|dir_env), poblacion, provincia)>
<!ATTLIST datos_cliente n_cli ID #REQUIRED>
<!ELEMENT datos_factura (fecha, linea+, base, cuota_iva, total)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT base (#PCDATA)>
<!ELEMENT cuota_iva (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ATTLIST datos_factura
	n_ped ID #REQUIRED
	iva (16) #REQUIRED
	f_pago (efectivo|tarjeta|bizum) #REQUIRED
	moneda CDATA #FIXED "euro"
>
<!ELEMENT linea (ref, desc, cant, precio, importe)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT cant (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
]>
-->
<factura n_fac="n_999"> 
	<datos_empresa> 
		<nombre>Equipos Digitales S.L.</nombre> 
		<dir>Av. Valladolid</dir> 
		<poblacion cod_postal="28043">Madrid</poblacion> 
		<provincia>Madrid</provincia> 
		<cif>Q-9876543</cif> 
		<telefono>917776688</telefono>
		<fax>917776699</fax>
	</datos_empresa> 
	<datos_cliente n_cli="n_879"> 
		<nombre>Darío, Bueno Gutiérrez</nombre> 
		<dir_env>Av. Oporto nº7 4ºd</dir_env> 
		<poblacion cod_postal="28043">Madrid</poblacion> 
		<provincia>Madrid</provincia> 
	</datos_cliente> 
	<datos_factura n_ped="n_731" iva="16" f_pago= "efectivo" moneda="euro"> 
		<fecha>12-01-2005</fecha> 
		<linea> 
			<ref>MII93000F/8</ref> 
			<desc>MICRO PENTIUM IV 3000MHZ FB800</desc> 
			<cant>1</cant> 
			<precio>230</precio> 
			<importe>266.80</importe> 
		</linea> 
		<linea> 
			<ref>MB8QDIP4</ref> 
			<desc>PLACA BASE QDI P4</desc> 
			<cant>1</cant> 
			<precio>180</precio> 
			<importe>208.80</importe> 
		</linea> 
		<linea> 
			<ref>MEDD512M32</ref> 
			<desc>DIMM DDR 512MB 3200</desc> 
			<cant>2</cant> 
			<precio>40</precio> 
			<importe>92.80</importe> 
		</linea> 
		<linea> 
			<ref>HD250GSA7</ref> 
			<desc>DISCO DURO 250GB S-ATA 7200</desc> 
			<cant>4</cant> 
			<precio>120</precio> 
			<importe>556.80</importe> 
		</linea> 
		<base>970.00</base> 
		<cuota_iva>155.20</cuota_iva>
		<total>1125.20</total> 
	</datos_factura>
</factura>
