=== sjimmaz322/Lenguaje-de-Marcas/Schema/notas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<aka:schema xmlns:aka="http://www.w3.org/2001/XMLSchema">
	<!-- aka puede ser lo que queramos -->
	<aka:element name="notas" type="notesType" />
	<aka:complexType name="notesType">
		<aka:sequence>
			<aka:element name="nota" type="noteType" minOccurs="0" maxOccurs="unbounded"/>
		</aka:sequence>
	</aka:complexType>

	<aka:element name="nota" type="noteType" />
	<aka:complexType name="noteType" mixed="true">
		<aka:sequence>
			<!-- sequence para mantener el orden, all para que el orden de igual -->
			<aka:element name="de" type="aka:string" />
			<aka:element name="para" type="aka:string" />
			<aka:choice>
				<aka:element name="titulo" type="aka:string" />
				<aka:element name="fecha" type="aka:date" />
			</aka:choice>
			<aka:element name="contenido" type="aka:string" />
		</aka:sequence>
	</aka:complexType>
</aka:schema>

<!-- otra forma de hacerlo
<aka:complexType>
		<aka:sequence>	
			<aka:element name="de" type="aka:string"/>
			<aka:element name="para" type="aka:string"/>
			<aka:element name="titulo" type="aka:string"/>
			<aka:element name="contenido" type="aka:string"/>
		</aka:sequence>
</aka:complexType>
-->

=== sjimmaz322/Lenguaje-de-Marcas/Schema/notas.xml
<?xml version="1.0" encoding="UTF-8"?>
<notas>
	<nota xmlns:akai="http://www.w3.org/2001/XMLSchema-instance" akai:noNamespaceSchemaLocation="notas.xsd">
		<de>Juan</de>
		<para>Pedro</para>
		<titulo>Recordatorio</titulo>
		<contenido>Compra pan</contenido>
	</nota>

	<nota xmlns:akai="http://www.w3.org/2001/XMLSchema-instance" akai:noNamespaceSchemaLocation="notas.xsd">
		<de>Juan</de>
		<para>Pedro</para>
		<fecha>01-01-2022</fecha>
		<contenido>Compra pan</contenido>
	</nota>
</notas>
