=== sjimmaz322/Lenguaje-de-Marcas/XML/Ejercicios/Relación_Final_ejercicios.xml/banco_lorca.dtd
<!ELEMENT banco (sucursal+)>
<!ELEMENT sucursal (cuenta+)>
<!ELEMENT cuenta (cliente+)>
<!ELEMENT cliente (nombre, apellidos, nivel,  prestamo*)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT prestamo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>

<!ATTLIST sucursal cod ID #REQUIRED>
<!ATTLIST cuenta cod_cuenta ID #REQUIRED>
<!ATTLIST cliente nif ID #REQUIRED>

=== sjimmaz322/Lenguaje-de-Marcas/XML/Ejercicios/Relación_Final_ejercicios.xml/banco_lorca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "banco_lorca.dtd">

<banco>
	<sucursal cod="Name">
		<cuenta cod_cuenta="Code">
			<cliente nif="nif">
				<nombre></nombre>
				<apellidos></apellidos>
				<nivel></nivel>
				<prestamo></prestamo>
			</cliente>
		</cuenta>
		<cuenta cod_cuenta="Code2">
			<cliente nif="nif2">
				<nombre></nombre>
				<apellidos></apellidos>
				<nivel></nivel>
				<prestamo></prestamo>
			</cliente>
		</cuenta>
	</sucursal>
</banco>
