<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE agenda SYSTEM "ejemplo-agenda.dtd">
<!--
Para el ejercicio 4:
DeberÃ­amos borrar el !DOCTYPE y sustituirlo por lo siguiente
 
<!DOCTYPE agenda [
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf)>
<!ATTLIST persona id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
]>

 -->
 
 <agenda>
 <persona id="E001">
 <nombre>Ricardo Borriquero</nombre>
 <tlf>951345678</tlf>
 </persona>
 <persona id="E002">
 <nombre>Eva Risto</nombre>
 <tlf>955837659</tlf>
 </persona>
 </agenda>
